services:
  
  webserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - users_api
    networks:
      - dev_network

  users_api:
    build:
      context: ./APIS
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 2GB
        reservations:
          cpus: '0.1'
          memory: 1GB
    ports:
      - "3000:3000"  # Solo una instancia mapeada a este puerto
    volumes:
      - ./APIS/usuarios:/usr/userAPI
    env_file:
      - ./APIS/usuarios/.env
    depends_on:
      - db_dev
    networks:
      - dev_network

  db_dev:
    build:
      context: .  # Contexto en la raíz del proyecto
      dockerfile: APIS/Dockerfile.postgres_base
    container_name: users_db_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario          
      POSTGRES_PASSWORD: 12345        
      POSTGRES_DB: calorias_db        
    volumes:
      - ./users_data_dev:/var/lib/postgresql/data
      - ./users_logs:/var/log/postgresql
      - ./postgresql_configs/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresql_configs/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - dev_network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jhonatan.diazv@campusucc.edu.co
      PGADMIN_DEFAULT_PASSWORD: 12345
    depends_on:
      - db_dev
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  users_data_dev:
